import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideNav from "../components/SideNav";
import { TasksProvider } from "@/context/TaskContext";
import { emptyState } from "@/context/TaskReducer";
import { ToastProvider } from "@/context/ToastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TasksProvider emptyState={emptyState}>
          <ToastProvider>
            <div>
              <aside className="absolute h-full min-h-screen w-16">
                <SideNav />
              </aside>
              <div className="ml-17 min-h-screen overflow-y-hidden bg-blue-700">
                {children}
              </div>
            </div>
          </ToastProvider>
        </TasksProvider>
      </body>
    </html>
  );
}
